# Generated by Django 5.2.4 on 2026-07-05 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alert', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='alert',
            name='privacy',
            field=models.CharField(choices=[('anyone', 'Anyone in HoodLink'), ('friends', 'Friends'), ('only_me', 'Only me')], default='anyone', max_length=20),
        ),
    ]
