# Generated by Django 5.2.4 on 2026-07-05 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alert', '0002_alert_privacy'),
    ]

    operations = [
        migrations.AddField(
            model_name='alert',
            name='title',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
