# Generated by Django 5.2.4 on 2026-07-21 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alert', '0003_alert_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='alert',
            name='is_anonymous',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='alert',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='alert_photos/'),
        ),
    ]
