# Generated by Django 6.0.6 on 2026-06-23 02:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='banner',
            new_name='event_banner',
        ),
    ]
