# Generated by Django 5.2.4 on 2026-07-15 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deal', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DealPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('billing_cycle', models.CharField(choices=[('monthly', 'Monthly'), ('yearly', 'Yearly')], default='monthly', max_length=50)),
                ('discount_offer', models.IntegerField(default=0)),
                ('active_deals_limit', models.IntegerField(default=1)),
                ('badge_text', models.CharField(blank=True, max_length=255, null=True)),
                ('is_most_popular', models.BooleanField(default=False)),
                ('features', models.JSONField(blank=True, default=list, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.RemoveField(
            model_name='dealphoto',
            name='deal',
        ),
        migrations.DeleteModel(
            name='Deal',
        ),
        migrations.DeleteModel(
            name='DealPhoto',
        ),
    ]
