# Generated by Django 5.2.4 on 2026-07-15 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deal', '0002_dealplan_remove_dealphoto_deal_delete_deal_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dealplan',
            name='active_deals_limit',
            field=models.IntegerField(blank=True, default=1, help_text='Set to null or leave blank for unlimited active deals.', null=True),
        ),
    ]
