# Generated by Django 5.2.4 on 2026-07-15 10:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deal', '0003_alter_dealplan_active_deals_limit'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Deal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('category', models.CharField(choices=[('Food', 'Food'), ('Retail', 'Retail'), ('Services', 'Services'), ('Beauty', 'Beauty'), ('Fitness', 'Fitness'), ('Automotive', 'Automotive'), ('Home Services', 'Home Services'), ('Family', 'Family')], max_length=50)),
                ('deal_type', models.CharField(choices=[('Percentage', 'Percentage'), ('Flat Discount', 'Flat Discount'), ('Buy One Get One', 'Buy One Get One'), ('Other', 'Other')], default='Percentage', max_length=50)),
                ('description', models.TextField(max_length=500)),
                ('business_name', models.CharField(max_length=255)),
                ('business_type', models.CharField(choices=[('Physical Location', 'Physical Location'), ('Online Service', 'Online Service')], default='Physical Location', max_length=50)),
                ('address', models.CharField(blank=True, max_length=255, null=True)),
                ('phone_number', models.CharField(max_length=50)),
                ('website', models.URLField(blank=True, null=True)),
                ('social_links', models.CharField(blank=True, max_length=255, null=True)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('terms_conditions', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_deals', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DealPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='deal_photos/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('deal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='deal.deal')),
            ],
        ),
    ]
