# Generated by Django 5.2.4 on 2026-07-16 02:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deal', '0005_deal_latitude_deal_location_name_deal_longitude'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='deal',
            name='call_clicks_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='deal',
            name='directions_clicks_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='deal',
            name='saves_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='deal',
            name='views_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.CreateModel(
            name='SavedDeal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('deal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_by_users', to='deal.deal')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_deals', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('user', 'deal')},
            },
        ),
    ]
