# Generated by Django 5.2.4 on 2026-07-16 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deal', '0006_deal_call_clicks_count_deal_directions_clicks_count_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='deal',
            name='impressions_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
