# Generated by Django 5.2.4 on 2026-07-16 03:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('deal', '0007_deal_impressions_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deal',
            name='impressions_count',
        ),
    ]
