# Generated by Django 5.2.4 on 2026-07-22 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='pickup_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
