# Generated by Django 5.2.4 on 2026-07-22 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listing', '0002_listing_pickup_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='pickup_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
