# Generated by Django 6.0.6 on 2026-06-22 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_otp'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='distance_radius',
            field=models.IntegerField(blank=True, default=25, null=True),
        ),
    ]
