# Generated by Django 5.2.4 on 2026-06-29 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_user_about_me'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='notify_events',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='user',
            name='notify_looking_for',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='user',
            name='notify_recommendations',
            field=models.BooleanField(default=True),
        ),
    ]
