# Generated by Django 5.2.4 on 2026-07-01 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_user_notify_events_user_notify_looking_for_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='location_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
