# Generated by Django 5.2.4 on 2026-07-08 04:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_user_location_name'),
        ('custom_admin', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='current_plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='custom_admin.subscriptionplan'),
        ),
        migrations.AddField(
            model_name='user',
            name='is_subscribed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='subscription_expiry',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
