# Generated by Django 5.2.4 on 2026-07-15 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_user_fcm_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='notify_business',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='user',
            name='notify_marketplace',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='user',
            name='notify_new_posts',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='distance_radius',
            field=models.FloatField(blank=True, default=25.0, null=True),
        ),
    ]
