# Generated by Django 5.2.4 on 2026-07-15 09:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_user_notify_business_user_notify_marketplace_and_more'),
        ('custom_admin', '0002_subscriptionplan_plan_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='current_deal_plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deal_users', to='custom_admin.subscriptionplan'),
        ),
        migrations.AddField(
            model_name='user',
            name='deal_subscription_expiry',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='is_deal_subscribed',
            field=models.BooleanField(default=False),
        ),
    ]
