# Generated by Django 5.2.4 on 2026-07-15 09:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_user_current_deal_plan_user_deal_subscription_expiry_and_more'),
        ('deal', '0002_dealplan_remove_dealphoto_deal_delete_deal_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='current_deal_plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='deal.dealplan'),
        ),
    ]
