# Generated by Django 5.2.4 on 2026-07-01 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('looking_for', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lookingfor',
            name='location_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
