# Generated by Django 5.2.4 on 2026-07-05 05:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('looking_for', '0002_lookingfor_location_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LookingForComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('looking_for', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='looking_for.lookingfor')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='looking_for_comments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='LookingForShare',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('looking_for', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shares', to='looking_for.lookingfor')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='looking_for_shares', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='LookingForLike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('looking_for', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='looking_for.lookingfor')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='looking_for_likes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('looking_for', 'user'), name='unique_looking_for_like')],
            },
        ),
    ]
