# Generated by Django 5.2.4 on 2026-07-09 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0002_businessrating'),
    ]

    operations = [
        migrations.RenameField(
            model_name='businessrating',
            old_name='comment',
            new_name='review',
        ),
        migrations.AlterField(
            model_name='businessrating',
            name='rating',
            field=models.IntegerField(),
        ),
    ]
