# Generated by Django 5.2.4 on 2026-07-09 09:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0003_rename_comment_businessrating_review_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BusinessRating',
        ),
    ]
