# Generated by Django 5.2.4 on 2026-07-22 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0005_businessprofile_businessprofilephoto'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='directions_clicks_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='business',
            name='views_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
