# Generated by Django 5.2.4 on 2026-07-15 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_admin', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptionplan',
            name='plan_type',
            field=models.CharField(choices=[('business', 'Business'), ('deal', 'Deal')], default='business', max_length=20),
        ),
    ]
