# Generated by Django 6.0.6 on 2026-06-23 05:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recommendations', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recommendation',
            name='recommendation_type',
        ),
        migrations.RemoveField(
            model_name='recommendation',
            name='suburb',
        ),
    ]
