# Generated by Django 5.2.4 on 2026-07-01 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommendations', '0002_remove_recommendation_recommendation_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='recommendation',
            name='location_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
